PACKAGE_NAME="a720-wmi-handshake"
PACKAGE_VERSION="1.0.0"
BUILT_MODULE_NAME[0]="a720_wmi_handshake"
DEST_MODULE_LOCATION[0]="/updates/dkms"
AUTOINSTALL="yes"
MAKE[0]="make KDIR=/lib/modules/${kernelver}/build"
CLEAN="make clean"
